package com.example.e_textilesendingserver.core.config

/**
 * Mirror of data_receive.py configuration，以默认值贴合现有 Python 桥。
 */
data class BridgeConfig(
    val udpListenPort: Int = 13250,
    val udpCopyLocal: Boolean = false,
    val localForwardIp: String = "127.0.0.1",
    val localForwardPort: Int = 53000,
    val udpBufferBytes: Int = 8192,
    val udpSocketBufferBytes: Int = 4 * 1024 * 1024,
    val publishRaw: Boolean = true,
    val publishParsed: Boolean = false,
    val batchMaxItems: Int = 50,
    val batchMaxMs: Long = 40,
    val batchSeparator: String = "NONE",
    val queueSize: Int = 2000,
    val dropOldest: Boolean = true,
    val brokerHost: String = "127.0.0.1",
    val brokerPort: Int = 1883,
    val clientId: String = "android-udp-bridge",
    val topicRaw: String = "etx/v1/raw",
    val topicParsedPrefix: String = "etx/v1/parsed",
    val mqttQos: Int = 1,
    val configCmdTopic: String = "etx/v1/config/cmd",
    val configResultTopic: String = "etx/v1/config/result",
    val configAgentTopic: String = "etx/v1/config/agents",
    val configAgentId: String = "agent-android",
    val deviceTcpPort: Int = 22345,
    val deviceTcpTimeoutSec: Double = 3.0,
    val registryTtlSec: Long = 300,
    val registryPublishSec: Long = 5,
    val statsIntervalMs: Long = 2000,
    val gcuEnabled: Boolean = true,
    val gcuSubscribeToken: String = "GCU_SUBSCRIBE",
    val gcuAckToken: String = "GCU_ACK",
    val gcuBroadcastToken: String = "GCU_BROADCAST",
    val gcuHeartbeatIntervalSec: Long = 5,
    val gcuFailoverSec: Long = 20,
    val gcuBroadcastOnStop: Boolean = true,
)
